//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _vistalibre.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class costos
    {
        public int id { get; set; }
        public Nullable<int> valor_inicial { get; set; }
        public Nullable<int> costo_final { get; set; }
        public Nullable<int> tipo_costo_id { get; set; }
        public Nullable<int> cotizacion_id { get; set; }
    
        public virtual tipo_costo tipo_costo { get; set; }
        public virtual cotizaciones cotizaciones { get; set; }
    }
}
