//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _vistalibre.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizaciones()
        {
            this.cotizaciones_complementarios = new HashSet<cotizaciones_complementarios>();
            this.vanos = new HashSet<vanos>();
        }
    
        public int id { get; set; }
        public Nullable<int> region_id { get; set; }
        public Nullable<int> tipo_vidrio_id { get; set; }
        public int descuento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizaciones_complementarios> cotizaciones_complementarios { get; set; }
        public virtual regiones regiones { get; set; }
        public virtual tipo_vidrio tipo_vidrio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vanos> vanos { get; set; }
    }
}
